### ISSUE TITLE
Table conversion

### ISSUE THREAD

**Issue by tsoratto** [ruggleslab/jukebox#10]
Hi,
I am trying to convert my humann2_genefamilies table to wham format using the script humann_2_wham.py, but I am getting this error:
Traceback (most recent call last):
  File "humann_2_wham.py", line 54, in <module>
    acc=R.group(2)
AttributeError: 'NoneType' object has no attribute 'group'

Thank you for your help.

**Comment by jcooperdevlin** [comment]
Hi!

Could you show the first few lines of the file you are trying to convert?

**Comment by tsoratto** [comment]
![image](https://user-images.githubusercontent.com/59020747/72528410-3a5c3900-386b-11ea-9477-d39af1509c4e.png)

**Comment by jcooperdevlin** [comment]
Thank you!

It appears from the first few lines the features do not have names, "Uniref50_unknown".
WHAM expects some kind of accession ID before the species name, for example...
"UniRef90_**C5EH42: Sporulation_protein_AB**|g__Clostridiales_noname.s__Clostridiales_1_7_47FAA"

Perhaps there was an issue with naming these features when running humann2_rename_table?
Feel free to attach the file so I can help troubleshoot further.

**Comment by tsoratto** [comment]
Thank you for the help!

Some of then is like you said and others no. I am attaching the file.

[humann2_pathabundance.txt](https://github.com/ruggleslab/jukebox/files/4072301/humann2_pathabundance.txt)

_

**Comment by jcooperdevlin** [comment]
Great, thank you!

The file you attached seems to be a pathway file which can be converted with a different script. humann_2_wham_pathways.py which should generate the appropriate WHAM file. However, you will need to add a "#" at the very beginning of the file to mark it as a humann2 output.

I hope that works!
