### ISSUE TITLE
page get disconnected from the server every time trying to upload input file

### ISSUE THREAD

**Issue by elffairy90** [ruggleslab/jukebox#14]
HIiiiiiiii there, 
![image](https://user-images.githubusercontent.com/49053347/106249099-dbd2e480-624c-11eb-829a-6d84939ec2ac.png)
everytime I'm trying to upload the input file, this weird thing happens, and if I click the "reload" button down the left bottom, it just restarts and the input file disappears again. I changed browser but it's still happening, and here is what the file looks like, I'm not sure why...should I remove the NAs or something?
![image](https://user-images.githubusercontent.com/49053347/106249342-379d6d80-624d-11eb-8285-40e9ca1088ec.png)

**Comment by jcooperdevlin** [comment]
Hi thank you for pointing this out!

unfortunately, I can't seem to locate the error from our server logs. However, it's likely the NAs are causing some issue but more likely the format is still direct from humann2. We recommend converting the format according to the documentation here... https://github.com/ruggleslab/jukebox/tree/master/wham_v1/file_conversion_scripts

If issues persist please share a small version of your data and I'd be happy to help troubleshoot.

**Comment by ne1al** [comment]
Could you replace the error "disconnected from server" to "incompatible format" for example? So the user intuitively knows something wrong with their files. I tried using the sample data you provided in your paper in the additional files section, I encountered the same error after converting it to tsv

**Comment by jcooperdevlin** [comment]
Done, updated the error for incompatible formats! Thanks for bringing this to our attention.
