### ISSUE TITLE
Adding groups by uploading csv file

### ISSUE THREAD

**Issue by jp589** [ruggleslab/jukebox#15]
Hello,

I'm interested in utilizing WHAM since I have metagenomic functional data, but I have several thousand samples. Since the group select tab only allows sample grouping by individually selecting samples from a list, I am unable to get past this step without spending hours selecting the correct samples.

If the intention is for others to use WHAM in their research, I would suggest adding functionality on the groups tab to allow a metadata file to be uploaded with a sample name column and a grouping column that would indicate the groups.

Thanks,

jp589

**Comment by jcooperdevlin** [comment]
Hi there,

The web browser was never designed to handle hundreds let alone thousands of metagenomic samples. This kind of processing power is not available on an Rshiny infrastructure. I encourage you to work with our R package to perform these calculations programmatically. The package can be found here https://github.com/zc1286/Wham

**Comment by jp589** [comment]
I see. I will take a look at the R package.

Thanks,

jp589
