### ISSUE TITLE
Conversion script

### ISSUE THREAD

**Issue by rachelmugge** [ruggleslab/jukebox#2]
Hello, I am trying to use the humann_2_wham_edit.py script to convert my gene table to the WHAM input format. I have used the humann_renorm_table script to convert from RPKs to CPM, and I have also removed the decimal values from the input table. The conversion script runs, but the output is simply the first row of my input file. I am not sure if this is an error on my end, or something in the conversion script. Thanks in advance! 

[RM_MG_renormed_table_cpm.txt](https://github.com/ruggleslab/jukebox/files/2299887/RM_MG_renormed_table_cpm.txt)
[wham_output.txt](https://github.com/ruggleslab/jukebox/files/2299888/wham_output.txt)

**Comment by rachelmugge** [comment]
Nevermind! There was a syntax error in the input file. Conversion and upload to WHAM was successful!

**Comment by kruggles7** [comment]
Great, glad you were able to resolve it!

**Comment by AnnaFos** [comment]
Hello! I am having exactly the same problem  but I cannot figure out if I have a syntax error - how did you eventually solve it? 
Many thanks!
