### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by lmanchon** [ruggleslab/jukebox#3]
--Hi,

i'm looking for manual or README file to install server on local system.

 thany you --

**Comment by jcooperdevlin** [comment]
Hi!

WHAM! can be run locally in an R session with the server.R, ui.R and global.R scripts listed in the source code on GitHub.

We host our application through shinyApps and therefore do not have a dedicated server as of yet. Does this answer your question?

**Comment by lmanchon** [comment]
yes, but how to load the R files ?  Do i need to put them in a dedicated folder ?
thank you --

**Comment by jcooperdevlin** [comment]
Yes, I suggest pulling the wham_v1 repository to your local computer and then opening either the server.R or ui.R scripts in an rstudio session and selecting "Run App". This should work as long as all libraries and dependencies are installed.

**Comment by lmanchon** [comment]
ok, i'm going to do that.
And another question about Humann2 output files: I have 3 output files from Humann2 analysis:
- humann2_genefamilies.tsv
- humann2_pathabundance.tsv
- humann2_pathcoverage.tsv

which of them is required by wham ?

**Comment by jcooperdevlin** [comment]
The gene families or pathway abundance will work with WHAM! But you will need to run the appropriate conversation scripts listed in the source code, to go from humann2 to a wham ready file format.

**Comment by lmanchon** [comment]
seems not working with R version 3.5.1:
Warning message:
package ‘rPython’ is not available (for R version 3.5.1) 
> source("D:\\wham_v1\\global.R")
Error in library(rPython) : aucun package nommé ‘rPython’ n'est trouvé
> source("D:\\wham_v1\\ui.R")
Error in loadingLogo("https://www.youtube.com/watch?v=pIgZ7gMze7A", "wham_logo_trans.png",  : 
  impossible de trouver la fonction "loadingLogo"

**Comment by jcooperdevlin** [comment]
I believe you can comment out the rPython library. This should not effect the application.
However, I have not compiled our application as a standalone R package yet so there will be some dependencies that will need to be downloaded for specific R versions. WHAM! was built in R 3.4.1

**Comment by lmanchon** [comment]
okay good.
thank you --

**Comment by lmanchon** [comment]
something strange on windows, i sourced the 3 files with no problems:
source("D:\\wham_v1\\global.R")
source("D:\\wham_v1\\ui.R")
source("D:\\wham_v1\\server.R")

and nothing occurs

**Comment by jcooperdevlin** [comment]
I believe you would still need to run the actual application, "shiny::runApp()"

**Comment by lmanchon** [comment]
yes, it works now.
thank you so much.
