### ISSUE TITLE
conversion scripts failed

### ISSUE THREAD

**Issue by lmanchon** [ruggleslab/jukebox#5]
--Hi,

something happens with my input files:
 ./humann_2_wham.py humann2_genefamilies.tsv > wham_genefamilies.tsv
Traceback (most recent call last):
  File "./humann_2_wham.py", line 63, in <module>
    acc=R.group(2)
AttributeError: 'NoneType' object has no attribute 'group'

 ./humann_2_wham_pathways.py humann2_pathabundance.tsv > wham_pathabundance.tsv
Traceback (most recent call last):
  File "./humann_2_wham_pathways.py", line 62, in <module>
    gfam=R.group(2)
AttributeError: 'NoneType' object has no attribute 'group'

see subset of my tsv file in attachment.

thank you --
[subset_tsv.zip](https://github.com/ruggleslab/jukebox/files/2840428/subset_tsv.zip)

**Comment by jcooperdevlin** [comment]
Hi,

In your gene families file, the Uniref90 names are missing from the header of each line.
Accession:**Uniref_name**|taxa
1CMET2-PWY: N10-formyl-tetrahydrofolate biosynthesis|g__Bacteroides.s__Bacteroides_caccae

This can be added with humann2 functions, humann2_rename_table.

Your pathway abundances file is formatted correctly. 
The scripts I wrote did not account for the "UNINTEGRATED" annotations. This has been updated in the source code. 

Hopefully this helps!

**Comment by lmanchon** [comment]
okay.
Please, can you try to upload my attached file here into your web application and see if it works fine ?
[humann2_pathabundance_wham.zip](https://github.com/ruggleslab/jukebox/files/2842613/humann2_pathabundance_wham.zip)

**Comment by jcooperdevlin** [comment]
Yes, it works.
I have also updated the source code, so I suggest pulling the repo again if you would like to use it locally.

**Comment by lmanchon** [comment]
- Hi,
thank you for the updates.
But it failed with my file with:

setwd(dir="D:/wham_v1")
library(randomcoloR)
library(webshot)
source("D:/wham_v1/global.R")
source("D:/wham_v1/ui.R")
source("D:/wham_v1/server.R")
shiny::runApp()
Listening on http://127.0.0.1:7201
Warning in fread(inFile$datapath, header = TRUE, sep = "\t") :
  Stopped early on line 381579. Expected 83 fields but found 0. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<Acc     Gene_Family     SpeciesM1: Ribosomal large subunit pseudouridine synthase B ## LSU Psi2605|unclassified 0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0.775566        0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0>>
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning in apply(nums, 1, as.integer) :
  NAs introduced by coercion to integer range
Warning: Error in quantile.default: missing values and NaN's not allowed if 'na.rm' is FALSE
  82: stop
  81: quantile.default
  79: <reactive:acc_full> [D:\wham_v1/server.R#391]
  63: acc_full
  62: <reactive:acc_select> [D:\wham_v1/server.R#502]
  46: acc_select
  44: <observer> [D:\wham_v1/server.R#518]
   1: shiny::runApp
Warning: Error in quantile.default: missing values and NaN's not allowed if 'na.rm' is FALSE
  100: <Anonymous>

you can download my file from this link: 
https://filesender.renater.fr/?s=download&token=a090cee0-8ca0-bb1f-d92e-8caf71070c26

**Comment by jcooperdevlin** [comment]
It looks like the attached file has a number of formatting issues.
By viewing the file in a text editor I noticed several empty lines and lines with a repeating header "Acc \t Gene_Family \t Species". Many of these lines also contained special characters, such as '#'.
Additionally, there were duplicate sample names in the header, in some cases 3 or 4 instances.

I removed the lines with special characters, empty lines and repeating headers and also renamed the sample names.  The file is too large to attach but here is a subset.
[genes_wham_small.tsv.zip](https://github.com/ruggleslab/jukebox/files/2869982/genes_wham_small.tsv.zip)

I was able to get this to work, but also made some corrections to the count estimation so you should pull the repo again.

**Comment by lmanchon** [comment]
--
Indeed I made a mistake with the wrong file, they are not the right headers.
In fact my Humann2 output file is formatted with 80 columns that correspond to 80 samples, and all the values are reported in RPK. 
To understand, there are several samples per patient. I have a total of 24 patients.
In the attached file you will be able to see an extract from the file that corresponds to the first 1000 lines of the genefamilies file output . And there is also the file of metadata associated with the samples.
In wham we can't do more than 10 groups to compare them. I would like to know (or classify) the population of bacteria (taxon) most represented by patients.
The problem is that I have 24 patients (24 groups). To do this kind of analysis, should I use the file 'humann2_genefamilies.tsv' file or the 'humann2_pathabundance.tsv' file ? 
Thank you --
[Downloads.zip](https://github.com/ruggleslab/jukebox/files/2870214/Downloads.zip)
