### ISSUE TITLE
Unable to upload TSV File

### ISSUE THREAD

**Issue by joshuacgil** [ruggleslab/jukebox#6]
--Hi,

Forgive me if this is something I am overlooking but I am trying to upload a TSV in the upload tab and It doesn't seem to recognize .tsv, only .csv and .txt. I have downloaded the sample file to test this, thinking that maybe it was my files were possibly messed up but when i hit browse the sample.tsv file is not recognized either. Any help would be greatly appreciated!  

-Thanks!

**Comment by jcooperdevlin** [comment]
Is it possible you are using an unsupported browser? File uploads to RShiny have some restrictions in browsers like Safari.
Have you tried Chrome?

**Comment by joshuacgil** [comment]
I am using chrome. I'll try another browser though, perhaps firefox?

**Comment by jcooperdevlin** [comment]
Chrome should work, would you mind sharing a small subset of your input file?
I have checked the sample.tsv file just a few minutes ago and I have no upload issues in chrome.

When you attempt to upload a new file from the "Browse" button are ".tsv" files simply greyed out or is an error thrown upon uploading? If there is an error please share that as well

Thanks!

**Comment by joshuacgil** [comment]
ok so this is embarrassing I thought the file search was already set to select "all files" but it was set to "custom files" so i found it and was able to upload it. Thank you for the help anyhow and sorry if i took up any of your time.
