### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by utritala** [ruggleslab/jukebox#7]
Hi,
I am having trouble with conversion script "humann_2_wham.py".When I try to run this, I get following error: 
```
File "humann_2_wham.py", line 44
    heading = things[0]
                      ^
IndentationError: unindent does not match any outer indentation level
```

Please can you help? 

Many thanks.

**Comment by jcooperdevlin** [comment]
Hi, 
Happy to help!
Can you provide the first few lines of your input file?
And describe how it was processed.

Thanks!

**Comment by utritala** [comment]
Hi,
Thank you for your reply. There was an indentation error because of a
mixture of tabs and spaces in the indents. I have fixed this and it worked
fine. :)

**Comment by jcooperdevlin** [comment]
I see, well glad it was an easy fix!
If you have any questions in the future please let us know!
