### ISSUE TITLE
Conversion script Used on Path Abundance TSV

### ISSUE THREAD

**Issue by grajimen** [ruggleslab/jukebox#9]
Hello,

I am running into an issue when I try to use the python conversion script to convert my humann2_pathabundance.tsv file into a wham-friendly tsv file. After a bit of guidance I was able to use wham for my genefamilies tsv file from humann2, but I am not sure if I missed an additional required step for path abundance.

I run the following code:
`python humann_2_wham.py humann2_pathabundance_named.tsv > wham_pathabundance_named.tsv`

And I get the following error:
Traceback (most recent call last):
  File "humann_2_wham.py", line 54, in <module>
    acc=R.group(2)
AttributeError: 'NoneType' object has no attribute 'group'

Prior to running this python script, I have also used humann2_rename_table, humann2_renorm_table, and finally humann2_join_tables.  I have attached my TSV file that resulted from the humann2 steps mentioned, as well as the file that was generated when I ran the python conversion script.  Only the first line was generated from the conversion script, but it looks like the term species was inserted in the name of my first sample and I am not sure what might cause that.  Thank you in advance for any help or input!

[humann2_pathabundance_named subset.txt](https://github.com/ruggleslab/jukebox/files/3526786/humann2_pathabundance_named.subset.txt)

[wham_pathabundance_named.txt](https://github.com/ruggleslab/jukebox/files/3526819/wham_pathabundance_named.txt)

**Comment by jcooperdevlin** [comment]
There is a second script for pathway tables. I apologize it should be more clear in the usage information. This script is called humann_2_wham_pathway.py and can be found in the same place on GitHub.

**Comment by grajimen** [comment]
That did update my output so that Species is no longer inserted within a column name, but for some reason there is still only a header row that is output by the conversion script.

After updating my code to:
`python humann_2_wham_pathways.py humann2_pathabundance_named.tsv > wham_pathabundance_named.tsv`
I get the attached output file.  (Input is still same humann2 file attached to previous comment).  I am not sure if I should have formatted my input file differently or updated the wham_pathways script to include another option.

[wham_pathabundance_named.txt](https://github.com/ruggleslab/jukebox/files/3526974/wham_pathabundance_named.txt)
